_BASE_: "../Base-Memory-RCNN-FPN.yaml"
OUTPUT_DIR: "results/resnet50"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1230
    TEMP_S: 48
    MIN_CACHE: 20 
    MAX_CACHE: 60
    RANDOM_SELECT: False
    CACHE_CAT_FILE: "lvis_categories_lists/lvis0.5_rare_common30_cats.txt"
    CLS_LAYER: "cosine"
    RUN: 1
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train",)
  TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300 # LVIS allows up to 300
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
